backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads

slug:
  encoding: "ascii"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "list" }
      - { label: "Tags", name: "tags", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
